# File: mkdocs.yml
site_name: COVID and MPOX Data API
site_description: Documentation for the COVID and MPOX Data API
site_author: Your Name
repo_url: https://github.com/yourusername/covid-mpox-api
repo_name: covid-mpox-api

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.annotate
    - search.suggest
    - search.highlight
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - toc:
      permalink: true
      
plugins:
  - search
  - mkdocstrings

nav:
  - Home: index.md
  - Getting Started: 
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
    - Authentication: getting-started/authentication.md
  - API Reference:
    - Overview: api/overview.md
    - COVID Data: api/covid.md
    - MPOX Data: api/mpox.md
    - Statistics: api/statistics.md
  - Guides:
    - Using the API: guides/using-the-api.md
    - Data Integration: guides/data-integration.md
    - TypeScript Client: guides/typescript-client.md
  - Development:
    - Contributing: development/contributing.md
    - API Structure: development/api-structure.md
  - API Playground: https://yourdomain.com/api/docs

# File: docs/index.md
# COVID and MPOX Data API Documentation

Welcome to the documentation for the COVID and MPOX Data API. This API provides access to epidemic data with both public endpoints and protected endpoints requiring authentication.

## Features

- **Public Data Access**: Basic epidemic data available without authentication
- **Protected API**: Full data access and management with authentication
- **Comprehensive Data**: Complete COVID-19 and MPOX statistics 
- **Easy Integration**: RESTful API with JSON responses
- **TypeScript Support**: Type definitions for all endpoints and data models

## Quick Links

- [API Reference](api/overview.md) - Detailed documentation of all API endpoints
- [Getting Started](getting-started/installation.md) - Installation and configuration guides
- [API Playground](https://yourdomain.com/api/docs) - Interactive API documentation with Redoc

## Support

If you have questions or need help, please:

- [Open an issue](https://github.com/yourusername/covid-mpox-api/issues) on GitHub
- Contact the API team at [api-support@yourdomain.com](mailto:api-support@yourdomain.com)

# File: docs/api/overview.md
# API Overview

The COVID and MPOX Data API provides endpoints for retrieving and managing epidemic data. The API is divided into public endpoints that anyone can access and protected endpoints that require authentication.

## Base URL

All API endpoints are relative to:

```
https://yourdomain.com/api
```

## Authentication

Protected endpoints require authentication using a bearer token. Include the token in the Authorization header:

```
Authorization: Bearer your-api-token
```

## Response Format

All responses are returned in JSON format. Successful responses typically return the requested data or a success message. Error responses include an error message.

### Success Response Example

```json
{
  "success": true,
  "message": "Data added successfully"
}
```

### Error Response Example

```json
{
  "error": "Access denied. No token provided."
}
```

## API Documentation

For interactive API documentation, visit our [API Playground](https://yourdomain.com/api/docs) powered by Redoc.

## Endpoints Summary

| Endpoint | Method | Description | Authentication |
|----------|--------|-------------|----------------|
| `/covid/public/latest` | GET | Get latest COVID data | No |
| `/covid/public/country/:country` | GET | Get COVID data by country | No |
| `/covid/public/totals` | GET | Get global COVID totals | No |
| `/mpox/public/summary` | GET | Get MPOX summary | No |
| `/covid/data` | GET | Get all COVID data | Yes |
| `/covid/data` | POST | Add new COVID data | Yes |
| `/covid/data/:id` | PUT | Update COVID data | Yes |
| `/covid/data/:id` | DELETE | Delete COVID data | Yes |
| `/mpox/data` | GET | Get all MPOX data | Yes |
| `/mpox/data` | POST | Add new MPOX data | Yes |
| `/mpox/data/:id` | PUT | Update MPOX data | Yes |
| `/mpox/data/:id` | DELETE | Delete MPOX data | Yes |
| `/stats/summary` | GET | Get statistics summary | Yes |